### ISSUE TITLE
Comentarios en el Admin

### ISSUE THREAD

**Issue by Nicomagg** [leferreyra/django-tsg#44]
Agregar una seccion o pagina donde el administrador vea los comentario de los usuarios sobre los articulos

**Comment by leferreyra** [comment]
Esto esta basicamente, lo unico que falta es ver alguna forma no tan ciruja de ver que posts tienen los ultimos comentarios y ponerlos arriba.

**Comment by Nicomagg** [comment]
Esto se puede cerrar @leferreyra o le falta algo mas todavía?? Vamos a ver alguna forma de ordenarlos o lo dejamos así nomas??

**Comment by francom77** [comment]
Mañana lo vemos, para mi va a ser mas facil mostrar comments en rangos temporales que ordenar todo. Mañana hablamos y decidimos.

**Comment by Nicomagg** [comment]
Ok. De una :+1: :D
