### ISSUE TITLE
Corregir buscador

### ISSUE THREAD

**Issue by francom77** [leferreyra/django-tsg#51]
debe direccionar a "/#/articulos/parametroDeBusqueda" cuando se presiona enter en el input

**Comment by francom77** [comment]
@leferreyra esto se debería bindear en el js del bloque no?

**Comment by leferreyra** [comment]
Claro, en el _bindEvents del bloque habria que bindear el evento submit del form del bloque de busqueda, y cambiar la url cuando se haga submit

**Comment by francom77** [comment]
Bueno. Y lo debería sacar al form. Porque en realidad no hace el get, sino que entra a la URL y ahí se hace el get. Mañana lo hago.
