### ISSUE TITLE
Generar 2 menus nuevos

### ISSUE THREAD

**Issue by Nicomagg** [leferreyra/django-tsg#55]

**Comment by Nicomagg** [comment]
Voy a empezar con el segundo que me faltaba. Se va a llamar menu_5

**Comment by Nicomagg** [comment]
Se acomodaron los templates del menu dentro de una carpeta menus para empezar a acomodar esta carpeta

**Comment by francom77** [comment]
Genial, voy a hacer lo mismo con la carpeta de mails y cuando haga una de articles con esa :D

**Comment by francom77** [comment]
No hiciste el push jaja

**Comment by Nicomagg** [comment]
No no, pasa que quiero terminar el menu y ahi hacer el push asi no les queda un menu nada que ver..jaja
